coverage:
  status:
    project:
      default:
        target: auto
        paths:
          - "src"
        if_ci_failed: ignore
        informational: true 
    patch:
      default:
        target: auto
        paths:
          - "src"
        if_ci_failed: ignore
        informational: true

ignore:
  - "hgdl/_version.py"

